<?php $scriptVersion="?v=201504230437"; ?>
<script src="/weberp/notifications/scripts/jquery-loader.js<?echo $scriptVersion?>"></script>
<script src="/weberp/notifications/sse/notifier.js<?echo $scriptVersion?>"></script>
<script src="/weberp/notifications/bower_components/toastr/toastr.js<?echo $scriptVersion?>"></script>
<link href="/weberp/notifications/app/css/style.css<?echo $scriptVersion?>" rel="stylesheet" />
<link href="/weberp/notifications/bower_components/toastr/toastr.min.css" rel="stylesheet" />